### PR TITLE
Update the website for 'modern' Django

### PR DESCRIPTION
**Pull request by lmoureaux**
**Do not merge yet**, we need a plan for server migration.

This updates the website to work with Python 3 and the latest stable Django, 3.0.3. Tested locally with packages from pip.

@akfaew do you recall why the `admin` module was disabled on the server? In my setup it appears to be required, so I changed it back.

### CODE REVIEW

**Comment by lmoureaux** [comment]
Also, my local setup is based on `manage.py`, so I couldn't test the `wgsi` and `fcgi` files

**Comment by lmoureaux** [comment]
Edit: Now based on Python 3 and Django 3.0.3

**Comment by akfaew** [comment]
Unfortunately I'm unable to provide any insights here, it was years ago...

**Comment by lmoureaux** [comment]
Turns out the website copy had the `admin` module enabled.

**Pull request closed without merging**
